version: '3.8'

services:
  watcherapi:
    image: yesimeren/project:watcherapi-v1
    ports:
      - "8082:80"
    networks:
      - watcher-network

  watcherui:
    image: yesimeren/project:watcherui-v3
    ports:
      - "8083:80"
    networks:
      - watcher-network

networks:
  watcher-network:
